#pragma checksum "..\..\..\windows\AuthorizationWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A94441DFDD69F54B99D74D3C02B811BB2957A019806554205EC1C2C5275FF70E"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using Project3Kurs;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Project3Kurs {
    
    
    /// <summary>
    /// AuthorizationWindow
    /// </summary>
    public partial class AuthorizationWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 17 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label LoginAuthorizationLabel;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LoginAuthorizationTextBox;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label PasswordAuthorizatoinLabel;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PasswordAuthorizationTextBox;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordAuthorizationPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AuthorizationButton;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonShowPassAuthorizationWindow;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon EyeWindow;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\windows\AuthorizationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonExitAuthorizationWindow;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Project3Kurs;component/windows/authorizationwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\windows\AuthorizationWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 15 "..\..\..\windows\AuthorizationWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.Border_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.LoginAuthorizationLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.LoginAuthorizationTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.PasswordAuthorizatoinLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.PasswordAuthorizationTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.PasswordAuthorizationPasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 7:
            this.AuthorizationButton = ((System.Windows.Controls.Button)(target));
            
            #line 34 "..\..\..\windows\AuthorizationWindow.xaml"
            this.AuthorizationButton.Click += new System.Windows.RoutedEventHandler(this.AuthorizationButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ButtonShowPassAuthorizationWindow = ((System.Windows.Controls.Button)(target));
            
            #line 37 "..\..\..\windows\AuthorizationWindow.xaml"
            this.ButtonShowPassAuthorizationWindow.Click += new System.Windows.RoutedEventHandler(this.ButtonShowPassAuthorizationWindow_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.EyeWindow = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 10:
            this.ButtonExitAuthorizationWindow = ((System.Windows.Controls.Button)(target));
            
            #line 41 "..\..\..\windows\AuthorizationWindow.xaml"
            this.ButtonExitAuthorizationWindow.Click += new System.Windows.RoutedEventHandler(this.ButtonExitAuthorizationWindow_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

